apiVersion: apps/v1
kind: Deployment
metadata:
  name: lulupay-build-system
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: backend
    environment: production
    version: "4.0.0"
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: "LuluPay Android White-Label Build System - Production Deployment"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lulupay-build-system
      component: backend
      environment: production
  template:
    metadata:
      labels:
        app: lulupay-build-system
        component: backend
        environment: production
        version: "4.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      # Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      
      # Service Account
      serviceAccountName: lulupay-service-account
      
      # Image Pull Secrets
      imagePullSecrets:
        - name: docker-registry-secret
      
      # Init Containers for database migration and setup
      initContainers:
        - name: db-migration
          image: lulupay/build-system:4.0.0
          command: ["npm", "run", "migrate:up"]
          envFrom:
            - configMapRef:
                name: lulupay-config
            - secretRef:
                name: lulupay-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      
      # Main Application Container
      containers:
        - name: lulupay-build-system
          image: lulupay/build-system:4.0.0
          imagePullPolicy: Always
          
          # Ports
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          
          # Environment Configuration
          envFrom:
            - configMapRef:
                name: lulupay-config
            - secretRef:
                name: lulupay-secrets
          
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          
          # Resource Limits and Requests
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
            limits:
              memory: "2Gi"
              cpu: "1000m"
              ephemeral-storage: "10Gi"
          
          # Health Checks
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          
          startupProbe:
            httpGet:
              path: /api/health/startup
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            successThreshold: 1
          
          # Volume Mounts
          volumeMounts:
            - name: storage-builds
              mountPath: /app/storage/builds
            - name: storage-temp
              mountPath: /app/storage/temp
            - name: storage-assets
              mountPath: /app/storage/assets
            - name: logs
              mountPath: /app/logs
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: android-sdk
              mountPath: /opt/android-sdk
              readOnly: true
          
          # Security Context
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      
      # Volumes
      volumes:
        - name: storage-builds
          persistentVolumeClaim:
            claimName: lulupay-builds-pvc
        - name: storage-temp
          emptyDir:
            sizeLimit: 50Gi
        - name: storage-assets
          persistentVolumeClaim:
            claimName: lulupay-assets-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: lulupay-logs-pvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: android-sdk
          persistentVolumeClaim:
            claimName: android-sdk-pvc
      
      # Node Selection and Affinity
      nodeSelector:
        kubernetes.io/os: linux
        node-type: compute
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - lulupay-build-system
                topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - compute
                      - general
      
      # Tolerations
      tolerations:
        - key: "node-type"
          operator: "Equal"
          value: "compute"
          effect: "NoSchedule"
      
      # DNS Configuration
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "2"
          - name: edns0
      
      # Termination Grace Period
      terminationGracePeriodSeconds: 60
      
      # Priority Class
      priorityClassName: high-priority

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lulupay-build-system-hpa
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: autoscaler
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lulupay-build-system
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: active_builds
        target:
          type: AverageValue
          averageValue: "5"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lulupay-build-system-pdb
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: disruption-budget
    environment: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: lulupay-build-system
      component: backend
      environment: production

---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lulupay-service-account
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: service-account
    environment: production
automountServiceAccountToken: true

---
# Role for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lulupay-production
  name: lulupay-build-system-role
  labels:
    app: lulupay-build-system
    component: rbac
    environment: production
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]

---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lulupay-build-system-rolebinding
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: rbac
    environment: production
subjects:
  - kind: ServiceAccount
    name: lulupay-service-account
    namespace: lulupay-production
roleRef:
  kind: Role
  name: lulupay-build-system-role
  apiGroup: rbac.authorization.k8s.io 