apiVersion: v1
kind: Secret
metadata:
  name: lulupay-secrets
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: secrets
    environment: production
type: Opaque
data:
  # Database Credentials (base64 encoded)
  DB_USERNAME: bHVsdXBheV9wcm9k  # lulupay_prod
  DB_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>
  
  # Redis Password
  REDIS_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>
  
  # JWT and Session Secrets
  JWT_SECRET: <REPLACE_WITH_ACTUAL_BASE64_JWT_SECRET>
  SESSION_SECRET: <REPLACE_WITH_ACTUAL_BASE64_SESSION_SECRET>
  
  # API Keys
  ANDROID_SIGNING_KEYSTORE_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>
  GOOGLE_PLAY_API_KEY: <REPLACE_WITH_ACTUAL_BASE64_API_KEY>
  
  # Cloud Provider Credentials
  AWS_ACCESS_KEY_ID: <REPLACE_WITH_ACTUAL_BASE64_ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY: <REPLACE_WITH_ACTUAL_BASE64_SECRET_KEY>
  
  # Encryption Keys
  ASSET_ENCRYPTION_KEY: <REPLACE_WITH_ACTUAL_BASE64_ENCRYPTION_KEY>
  BUILD_ENCRYPTION_KEY: <REPLACE_WITH_ACTUAL_BASE64_ENCRYPTION_KEY>
  
  # External Service API Keys
  SENDGRID_API_KEY: <REPLACE_WITH_ACTUAL_BASE64_API_KEY>
  SLACK_WEBHOOK_URL: <REPLACE_WITH_ACTUAL_BASE64_WEBHOOK_URL>
  
  # Docker Registry Credentials
  DOCKER_REGISTRY_USERNAME: <REPLACE_WITH_ACTUAL_BASE64_USERNAME>
  DOCKER_REGISTRY_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: lulupay-secrets-staging
  namespace: lulupay-staging
  labels:
    app: lulupay-build-system
    component: secrets
    environment: staging
type: Opaque
data:
  # Database Credentials (base64 encoded)
  DB_USERNAME: bHVsdXBheV9zdGFnaW5n  # lulupay_staging
  DB_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>
  
  # Redis Password
  REDIS_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>
  
  # JWT and Session Secrets
  JWT_SECRET: <REPLACE_WITH_ACTUAL_BASE64_JWT_SECRET>
  SESSION_SECRET: <REPLACE_WITH_ACTUAL_BASE64_SESSION_SECRET>
  
  # API Keys
  ANDROID_SIGNING_KEYSTORE_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>
  GOOGLE_PLAY_API_KEY: <REPLACE_WITH_ACTUAL_BASE64_API_KEY>
  
  # Cloud Provider Credentials
  AWS_ACCESS_KEY_ID: <REPLACE_WITH_ACTUAL_BASE64_ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY: <REPLACE_WITH_ACTUAL_BASE64_SECRET_KEY>
  
  # Encryption Keys
  ASSET_ENCRYPTION_KEY: <REPLACE_WITH_ACTUAL_BASE64_ENCRYPTION_KEY>
  BUILD_ENCRYPTION_KEY: <REPLACE_WITH_ACTUAL_BASE64_ENCRYPTION_KEY>
  
  # External Service API Keys
  SENDGRID_API_KEY: <REPLACE_WITH_ACTUAL_BASE64_API_KEY>
  SLACK_WEBHOOK_URL: <REPLACE_WITH_ACTUAL_BASE64_WEBHOOK_URL>
  
  # Docker Registry Credentials
  DOCKER_REGISTRY_USERNAME: <REPLACE_WITH_ACTUAL_BASE64_USERNAME>
  DOCKER_REGISTRY_PASSWORD: <REPLACE_WITH_ACTUAL_BASE64_PASSWORD>

---
# TLS Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: lulupay-tls
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: tls
    environment: production
type: kubernetes.io/tls
data:
  tls.crt: <REPLACE_WITH_ACTUAL_BASE64_CERTIFICATE>
  tls.key: <REPLACE_WITH_ACTUAL_BASE64_PRIVATE_KEY>

---
# Docker Registry Pull Secret
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: registry
    environment: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <REPLACE_WITH_ACTUAL_BASE64_DOCKER_CONFIG>

---
# Service Account Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: lulupay-service-account-token
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: service-account
    environment: production
type: kubernetes.io/service-account-token
data:
  token: <REPLACE_WITH_ACTUAL_BASE64_TOKEN>

---
# External DNS Secret for Route53 (if using)
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: lulupay-production
  labels:
    app: lulupay-build-system
    component: external-dns
    environment: production
type: Opaque
data:
  aws-access-key-id: <REPLACE_WITH_ACTUAL_BASE64_ACCESS_KEY>
  aws-secret-access-key: <REPLACE_WITH_ACTUAL_BASE64_SECRET_KEY> 