global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lulupay-production'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # LuluPay Build System - Main Application
  - job_name: 'lulupay-build-system'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'host.docker.internal:9090'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System Metrics
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\\d+'
        target_label: instance
        replacement: '${1}'

  # cAdvisor - Container Metrics
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'container_.*'
        target_label: __name__
        replacement: 'lulupay_${0}'

  # Redis Exporter
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # Elasticsearch Exporter
  - job_name: 'elasticsearch'
    scrape_interval: 30s
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Grafana Self-Monitoring
  - job_name: 'grafana'
    scrape_interval: 30s
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # AlertManager Self-Monitoring
  - job_name: 'alertmanager'
    scrape_interval: 30s
    static_configs:
      - targets: ['alertmanager:9093']

  # Kubernetes API Server (if running in K8s)
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
            - lulupay-production
            - lulupay-staging
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Nodes (if running in K8s)
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pods (if running in K8s)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - lulupay-production
            - lulupay-staging
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # LuluPay Partner Portal
  - job_name: 'lulupay-partner-portal'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/api/metrics'

  # LuluPay Asset Processing Service
  - job_name: 'lulupay-asset-service'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9001']
    metrics_path: '/metrics'

  # LuluPay Build Queue Service
  - job_name: 'lulupay-build-queue'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9002']
    metrics_path: '/metrics'

  # External Dependencies Monitoring
  - job_name: 'external-apis'
    scrape_interval: 60s
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.github.com
        - https://registry.npmjs.org
        - https://hub.docker.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Database Monitoring (if using external DB)
  - job_name: 'postgres-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Load Balancer Monitoring
  - job_name: 'nginx-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Custom Business Metrics
  - job_name: 'lulupay-business-metrics'
    scrape_interval: 60s
    static_configs:
      - targets: ['host.docker.internal:9003']
    metrics_path: '/business-metrics'

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 90d
    retention.size: 10GB
    wal-compression: true

# Remote write configuration (optional - for long-term storage)
remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      max_retries: 3 